version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walletdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ../backend/express-api
      dockerfile: Dockerfile
    env_file:
      - ../backend/express-api/.env
    ports:
      - "3001:3000"
    depends_on:
      - db
volumes:
  db_data:
